# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hello_world/hello_world.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_world || ORIG_REF_NAME==hello_world} -quiet] -quiet

# IP: bd/hello_world/ip/hello_world_processing_system7_0_0/hello_world_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_world_processing_system7_0_0 || ORIG_REF_NAME==hello_world_processing_system7_0_0} -quiet] -quiet

# XDC: bd/hello_world/hello_world_ooc.xdc
