# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Masters/APLC/Project/PLC_project/PLC_project.srcs/sources_1/bd/PLC_project/ip/PLC_project_processing_system7_0_0/PLC_project_processing_system7_0_0.xci
# IP: The module: 'PLC_project_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Masters/APLC/Project/PLC_project/PLC_project.srcs/sources_1/bd/PLC_project/ip/PLC_project_processing_system7_0_0/PLC_project_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLC_project_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Masters/APLC/Project/PLC_project/PLC_project.srcs/sources_1/bd/PLC_project/ip/PLC_project_processing_system7_0_0/PLC_project_processing_system7_0_0.xci
# IP: The module: 'PLC_project_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Masters/APLC/Project/PLC_project/PLC_project.srcs/sources_1/bd/PLC_project/ip/PLC_project_processing_system7_0_0/PLC_project_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLC_project_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
