# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PLC_project/PLC_project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLC_project || ORIG_REF_NAME==PLC_project} -quiet] -quiet

# IP: bd/PLC_project/ip/PLC_project_processing_system7_0_0/PLC_project_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLC_project_processing_system7_0_0 || ORIG_REF_NAME==PLC_project_processing_system7_0_0} -quiet] -quiet

# XDC: bd/PLC_project/PLC_project_ooc.xdc
